# Numpy Arrays


In [1]:
import numpy as np

In [4]:
# numoy has vectors 1D arrays and Matrix a 2D array
# arange returns an array with evenly spaced from 0 till 9 and 2 steps each time
np.arange (0,10,2)

array([0, 2, 4, 6, 8])

In [7]:
# Zeros and Ones matrices
np.zeros(3) # returs 3 columns

np.zeros((5,5)) # returns 5 by 5 matrix of zeros

np.ones((3,3)) # returns a 3 by 3 matrix of ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# Linespace takes the number of points you want
np.linspace(0,10,3) # returns 3 points between 0 and 10

In [10]:
# Eye returns an identity matrix of ones and zeros
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
# random numbers uniformly distributed from 0 to 1 
np.random.rand(2)

array([0.32187667, 0.2696509 ])

In [13]:
np.random.rand(5,5)

array([[0.82028624, 0.19787907, 0.74669766, 0.53440767, 0.73893071],
       [0.00981923, 0.88704291, 0.44443267, 0.21608985, 0.91462516],
       [0.81800842, 0.77333558, 0.97562358, 0.8448426 , 0.79415131],
       [0.0333405 , 0.58814529, 0.67913969, 0.58074271, 0.02418317],
       [0.71199097, 0.06036833, 0.95524873, 0.17295241, 0.9854252 ]])

In [14]:
# To get samples fromstandars normal distribution
np.random.randn(2,2)

array([[-0.25171459,  0.29421803],
       [ 0.57696401,  0.29404567]])

In [15]:
# Random Int between 1 and 99 and 10 elements
np.random.randint(1,100,10)

array([82, 51, 56, 88, 99, 53, 28, 24, 35, 59])

In [16]:
arr = np.arange(25)

In [17]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [18]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

# NumPy Indexing And Selection

In [19]:
#Setting a value with index range (Broadcasting)
arr = np.arange(0,11)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [20]:
# Selection

arr > 9

array([ True,  True,  True,  True,  True, False, False, False, False,
       False,  True])

In [21]:
arr[arr > 9]

array([100, 100, 100, 100, 100,  10])

# NumPy Operations

In [23]:
arr = np.arange(0,10)

In [24]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [25]:
np.max(arr)

9